# Generated by Django 6.0 on 2026-01-09 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_options_alter_roles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de Ciudad')),
                ('slug', models.SlugField(max_length=30, verbose_name='Slug')),
            ],
            options={
                'verbose_name': '4. Ciudad',
                'verbose_name_plural': '4. Ciudades',
                'db_table': 'ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=11, null=True, verbose_name='Telefono')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('pais', models.CharField(choices=[('ES', 'ESPAÑA'), ('FR', 'FRANCIA'), ('EN', 'INGLATERRA')], default='ES', help_text='(Obligatorio)', max_length=3, verbose_name='País')),
                ('edad', models.PositiveIntegerField(choices=[(18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=18, help_text='(Obligatorio)', verbose_name='Edad')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ciudades', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': '3. Dato',
                'verbose_name_plural': '3. Datos',
                'db_table': 'Informacion',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.infopersonal'),
        ),
    ]
