# Generated by Django 6.0 on 2026-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_ciudades_infopersonal_customuser_personal_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudades',
            options={'ordering': ['nombre'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
    ]
