# Generated by Django 6.0 on 2026-01-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_ciudades_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='default',
            field=models.BooleanField(default=False, verbose_name='¿Rol por Defecto?'),
        ),
    ]
